name: Deployment1

on:
  push:
    branches: [development, master]

jobs:
  Build_Development:
    if: ${{ github.ref == 'refs/heads/development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NPM
        run: sudo npm install -g npm@10.2.3
        
      - name: Install dependencies
        run: |
          echo Installing source NPM dependencies...
          sudo npm install --force

      - name: Buid the application
        env:
          CI: false
        run: sudo npm run build:prod
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-development
          path: build

  Build_Master:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NPM
        run: sudo npm install -g npm@10.2.3
        
      - name: Install dependencies
        run: |
          echo Installing source NPM dependencies...
          sudo npm install --force

      - name: Buid the application
        env:
          CI: false
        run: sudo npm run build:prod
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-master
          path: build

  Deploy_Development:
    needs: Build_Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-development
          path: build

      - name: Deploy to Development
        env:
          PRIVATE_KEY: ${{ secrets.LIFE_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.LIFE_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.LIFE_HOSTNAME }}:/tmp/Life_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.LIFE_HOSTNAME }} '
            sudo rm -rf /var/www/html/Life_fe/build &&
            sudo mv /tmp/Life_fe_build /var/www/html/Life_fe/build &&
            cd /var/www/html/Life_fe &&
            sudo git fetch origin &&
            sudo git checkout development &&
            sudo git pull origin development
          '

  Deploy_Master:
    needs: Build_Master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-master
          path: build

      - name: Deploy to Production
        env:
          PRIVATE_KEY: ${{ secrets.LIFE_PROD_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.LIFE_PROD_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.LIFE_PROD_HOSTNAME }}:/tmp/life_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.LIFE_PROD_HOSTNAME }} '
            sudo rm -rf /var/www/html/Life-fe/build &&
            sudo mv /tmp/life_fe_build /var/www/html/Life-fe/build &&
            cd /var/www/html/Life-fe &&
            sudo git checkout master &&
            sudo git pull origin master
          '
