
name: Deployment1

on:
  push:
    branches: development
jobs:
  
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NPM
        run: sudo npm install -g npm@10.2.3
        
      - name: Set legacy-peer-deps
        run: sudo npm config set legacy-peer-deps true
        
      - name: Install dependencies
        run: |
          echo Installing source NPM dependencies...
          sudo npm install --force

      - name: Buid the application
        env:
          CI: false
        run: sudo npm run build:dev
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  Deploy:
    
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Development
        if: github.ref == 'refs/heads/development'
        env:
          PRIVATE_KEY: ${{ secrets.LIFE_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.LIFE_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          #scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.LIFE_HOSTNAME }}:/tmp/Life_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.LIFE_HOSTNAME }} '
            #sudo rm -rf /var/www/html/a_fe/build &&
            #sudo mv /tmp/aim_fe_build /var/www/html/Life_fe/build &&
            cd /var/www/html/Life_fe &&
            sudo git fetch origin &&
            sudo git checkout development &&
            sudo git pull origin development
            '



          

            
