name: Deployment1

on:
  push:
    branches: [development, master]

jobs:
   Build_Master:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js 22.13.1
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Verify Node.js and NPM versions
        run: |
          node -v
          npm -v
      
      - name: Install NPM
        run: sudo npm install -g npm@10.9.2
      
      - name: Install dependencies
        run: |
          echo Installing source NPM dependencies...
          sudo npm install --force
        
      
      - name: Buid the application
        env:
          CI: false
        run: sudo npm run build:prod
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-master
          path: build


   Deploy_Master:
    needs: Build_Master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-master
          path: build

      - name: Deploy to Production
        env:
          PRIVATE_KEY: ${{ secrets.LIFE_PROD_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.LIFE_PROD_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.LIFE_PROD_HOSTNAME }}:/tmp/life_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.LIFE_PROD_HOSTNAME }} '
            sudo rm -rf /var/www/html/Life-FE-1/build &&
            sudo mv /tmp/life_fe_build /var/www/html/Life-FE-1/build &&
            cd /var/www/html/Life-FE-1 &&
            sudo git checkout master &&
            sudo git pull origin master
          '
